### ISSUE TITLE
Definition list renders as <div>

### ISSUE THREAD

**Issue by sethlivingston** [wataru-chocola/remark-definition-list#50]
I'm using this remark plugin in [astro](https://astro.build), which uses remark under the hood. The plugin is working and has changed how my Markdown definition lists get rendered, but it's rendering them as div elements:

```markdown
Pre-processing
: Happens when the request is malformed
```

```html
<div>Pre-processing</div>
<div><p>Happens when the request is malformed</p></div>
```

(I know the p element does not come from your plugin.)

Am I missing something?

**Comment by sethlivingston** [comment]
This appears to be something related to Astro. As far as I can tell, your plugin is working just fine.

**Comment by delucis** [comment]
Just to follow up in case anyone else looks for how to get this working in Astro. The issue was that `defListHastHandlers` wasn’t being passed to `remark-rehype` as shown [in the README for this package](https://github.com/wataru-chocola/remark-definition-list#use).

Configuring this looks slightly different in Astro from with a standard `unified.use(...)` chain, so sharing that here:

```js
// astro.config.mjs

import { defineConfig } from 'astro/config';
import {
  remarkDefinitionList,
  defListHastHandlers,
} from 'remark-definition-list';

export default defineConfig({
  markdown: {
    remarkPlugins: [remarkDefinitionList],
    remarkRehype: {
      handlers: {
        ...defListHastHandlers,
      },
    },
  },
});
```

Here’s a working example: https://stackblitz.com/edit/github-xpyk5h?file=astro.config.mjs

**Comment by bcullman** [comment]
I had this same issue, and the Astro Discord community came to the rescue! 

Here’s a working example
https://stackblitz.com/edit/github-xpyk5h?file=astro.config.mjs

Big 👏  to @delucis!
